\set ON_ERROR_STOP on
\set VERBOSITY verbose
\set ECHO all
CREATE SCHEMA IF NOT EXISTS staging AUTHORIZATION staging_owner;
CREATE SCHEMA IF NOT EXISTS ods AUTHORIZATION user_ods;
CREATE SCHEMA IF NOT EXISTS analytics AUTHORIZATION user_analytics;